-- AlterTable
ALTER TABLE "GlobalPricingSettings" ADD COLUMN     "pricesIncludeTax" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "taxEnabled" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "taxRate" SET DEFAULT 0.0;

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "pricesIncludeTax" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "subtotal" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "tax" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "taxEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "total" INTEGER NOT NULL DEFAULT 0;
